openapi: 3.0.0
info:
  title: Product API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/
    description: Optional server description, e.g. Main (production) server

components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
security:
  - basicAuth: []  # <-- use the same name here

paths:
  /api/products:
    post:
      summary: Create a product.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Coffee"
                price:
                  type: number
                  example: 5
      responses:
        '200':    # status code
          description: A JSON array of products
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "Coffee"
                    price:
                      type: number
                      example: 5
    get:
      summary: Returns a list of products.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of products
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "Coffe"
                    price:
                      type: number
                      example: 5

